[package]
name = "datafusion-sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "59.2.0"
arrow-arith = "59.2"
arrow-array = "59.2"
arrow-buffer = "59.2"
arrow-cast = "59.2"
arrow-data = "59.2"
arrow-ipc = "59.2"
arrow-row = "59.2"
arrow-schema = "59.2"
arrow-select = "59.2"
arrow-string = "59.2"
clap = { version = "4.6.1", features = ["derive"] }
datafusion = "54.1.0"
object_store = { version = "0.13.2", features = ["gcp"]}
vortex-datafusion = { git = "https://github.com/vortex-data/vortex", rev = "ba2ac36b1d7ff40083c187263ad7d49090e56d5b" }
vortex = { git = "https://github.com/vortex-data/vortex.git", rev = "ba2ac36b1d7ff40083c187263ad7d49090e56d5b" }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
futures = "0.3"
futures-util = "0.3"

[dev-dependencies]
divan = "0.1.21"

[profile.release]
# debug = true

[[bench]]
name = "example"
harness = false

[patch.crates-io]
datafusion = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-catalog = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-catalog-listing = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-common = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-common-runtime = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-datasource = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-datasource-arrow = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-datasource-avro = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-datasource-csv = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-datasource-json = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-datasource-parquet = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-doc = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-execution = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-expr = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-expr-common = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions-aggregate = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions-aggregate-common = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions-nested = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions-table = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions-window = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-functions-window-common = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-macros = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-optimizer = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-physical-expr = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-physical-expr-adapter = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-physical-expr-common = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-physical-optimizer = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-physical-plan = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-pruning = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-session = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-spark = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-sql = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
datafusion-sqllogictest = { git = "https://github.com/apache/datafusion", rev = "2bfdd4aea181525f5328781b29174d82be0c7fd4" }
